# Generated by Django 3.0 on 2022-02-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
                ('details', models.CharField(max_length=250)),
                ('syllebus', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=13)),
                ('qualification', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=5)),
                ('branch', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('sem', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=40)),
                ('timings', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('timing', models.CharField(max_length=40)),
                ('startdate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('Students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_installment', models.IntegerField()),
                ('second_installment', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
    ]
