# Generated by Django 3.0 on 2022-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enquiry', 'enquiry'), ('joined', 'joined'), ('complete', 'complete')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
