# Generated by Django 3.0 on 2022-02-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220207_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='first_installment_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='second_installment_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='total_fees',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
