# Generated by Django 3.0 on 2022-02-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220207_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edt',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
